// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://efmrlqdfqhxwizykvomt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVmbXJscWRmcWh4d2l6eWt2b210Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyNzY2MjQsImV4cCI6MjA3Mzg1MjYyNH0.ijxLwB5aMYGMVLOlfI9_LVvijzszK6jXrAnMzMM5J2o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});